global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.Options;
global using Moq;
global using Xunit;
global using FluentAssertions;
global using ECommerce.Infrastructure.Services;
global using ECommerce.Application.Interfaces;
global using ECommerce.Domain.Entities;
